name: Deploy to Development

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  STAGE: development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1

      - run: bundle config set path 'vendor/bundle' && bundle install
        working-directory: lambda/checker

      - run: bundle config set path 'vendor/bundle' && bundle install
        working-directory: lambda/pagerduty

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844815912454:role/GithubActions-Serverless-Lambda-Role
          aws-region: ${{ env.AWS_REGION }}

      - run: yarn global add serverless@3.0

      - run: make deploy-${{ env.STAGE }}
        env:
          PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
