name: Deploy to Development

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  STAGE: development
  TERRAFORM_VERSION: 1.13.4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1

      - run: bundle config set path 'vendor/bundle' && bundle install
        working-directory: lambda/checker

      - run: bundle config set path 'vendor/bundle' && bundle install
        working-directory: lambda/pagerduty

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844815912454:role/GithubActions-Serverless-Lambda-Role
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: terraform init -backend-config=../environments/${{ env.STAGE }}.backend.hcl
        working-directory: terraform

      - run: terraform apply -auto-approve -input=false -var-file=../environments/${{ env.STAGE }}.tfvars
        working-directory: terraform
